project:
  type: website

website:
  description: "My Personal Blog"
  site-url: https://derharsh.github.io/LupLup 
  repo-url: https://github.com/derharsh.io/LupLup
  title: "LupLup"
  navbar:
    right:
      - text: Notes
        href: library.qmd
      - text: Research
        href: research.qmd
      - about.qmd
      - icon: github
        href: https://github.com/derharsh.io/LupLup
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    math: katex