project:
  type: website

website:
  description: "My Personal Blog"
  site-url: https://derharsh.github.io/LupLup 
  repo-url: https://github.com/derharsh.io/LupLup
  title: "LupLup"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Notes
        href: library.qmd
      - text: Research
        href: research.qmd
      - about.qmd
      - icon: github
        href: https://github.com/derharsh/LupLup
comments: 
    giscus: 
        repo: derharsh/LupLup
        repo-id: R_kgDOJYJ4TA
        category: General
        category-id: DIC_kwDOQzOiLM4C0k3E
        mapping: pathname
        reactions-enabled: true
        input-position: top
        theme: noborder_dark
        language: en
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    math: katex